services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - JELLYFIN_PublishedServerUrl=http://localhost:8096
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ${MOVIES_PATH}:/media/movies:ro
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "987" # render
      - "983" # video
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 4G
